language: python

python:
  - "3.6"

env:
  - "NUMPY=1.16.4 SKLEARN=0.20.3 SCIPY=1.3.0"
  - "NUMPY=1.16.4 SKLEARN=0.21.2 SCIPY=1.3.0"

notifications:
  email: false

before_install:
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy=$NUMPY scikit-learn=$SKLEARN scipy=$SCIPY
  - pip install pytest pytest-cov codecov
  - python setup.py install

script:
  - pytest --cov=./

after_success:
  - codecov

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    user: sorenpypi
    password:
      secure: "Vv+1XPiwu54hP98z7iuE1Vx03rMk7AJoGDPPzAksRnY9219gWbO4RKwcjEz6RELrKstzKHpQBRjc1XdZvlQ/6jORl212adwjN9eK4M0zjk42X9XgFrbEnGUT2ONIMuPI6sCEyqwQDXkXxNS9xOZlqOhptg8X1pfqg5wChMJxOTk="
    on:
      branch: master
      tags: true
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    user: sorend
    password:
      secure: "AWlM4xK454gZWfxxxYMPVKR3/SlVEhza9mS81ExIa7EVkWiRmR3yFnCxtrISJ8fPGSh/eprC/X8VYa3ShJr+qNbm00q5VyY7qeKEyegM23Ejnf/mCPH5RCQCdeOWPhbWOyPtr5lN9E94Q9w8LNlpyb6mtU0h/RXrHSYuaEmPS1w="
    on:
      all_branches: true
