language: python

python:
  - "3.6"

env:
  - "NUMPY=1.16.4 SKLEARN=0.20.3 SCIPY=1.3.0"
  - "NUMPY=1.16.4 SKLEARN=0.21.2 SCIPY=1.3.0"

notifications:
  email: false

before_install:
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy=$NUMPY scikit-learn=$SKLEARN scipy=$SCIPY
  - pip install pytest pytest-cov codecov
  - python setup.py install

script:
  - py.test --cov=./

after_success:
  - codecov
